services:
  wallet:
    image: wallet_test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7500:7500
    environment: 
      - FLASK_RUN_PORT= 7500
      #- service_url= http://localhost:5000/
      - service_url= https://dev.tester.issuer.eudiw.dev/
