services:
  wallet:
    image: wallet_test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment: 
      - FLASK_RUN_PORT= 5000
      - service_url= http://localhost:5000/
      # - service_url: https://dev.tester.issuer.eudiw.dev/
